[workspace]
resolver = "1"
members = [
    "proton-wallet-common",
    "proton-wallet-mobile",
    "proton-wallet-web",
]
[profile.release]
opt-level = "s" # Tell `rustc` to optimize for small code size.
