[workspace]
resolver = "2"
members = [
    # "crates/api", # Muon is not ready yet
    "crates/common", # Muon is not ready yet
    "crates/bitcoin",
    # "crates/wasm", # Muon wasm depends on Muon
    # "examples/cli",
]
[profile.release]
opt-level = "s" # Tell `rustc` to optimize for small code size.
