[workspace]
resolver = "2"
members = [
    "crates/api",
    "crates/common",
    "crates/bitcoin",
    # "crates/wasm", # Muon wasm depends on Muon
    # "examples/cli",
]
[profile.release]
opt-level = "s" # Tell `rustc` to optimize for small code size.
