[package]
name = "andromeda-bitcoin"
version = "0.1.0"
edition = "2021"


[dependencies]
andromeda-common = { version = "0.1.0", path = "../common" }

serde = { version = "1.0.144", features = ["derive"] }
uuid = { version = "1.6.1", features = ["v4", "fast-rng"] }
urlencoding = "2.1.3"
querystring = "1.1.0"
futures = "0.3.30"

hashbrown = "0.9.1"

bitcoin = { version = "0.30.2", default-features = false, features = [
  "serde",
  "secp-recovery",
  "rand",
] }
miniscript = { version = "10.0.0", default-features = false }

bdk = { version = "0.29.0", default-features = false, features = [
  "std",
  "keys-bip39",
  "use-esplora-reqwest",
  "reqwest-default-tls",
  "async-interface",
] }
esplora-client = { version = "0.6.0", default-features = false, features = [
  'async-https',
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.10", features = ["js"] }
instant = { version = "0.1", features = ["wasm-bindgen"] }
wasm-bindgen = { version = "0.2.88", features = [
  "serde-serialize",
], optional = true }
wasm-bindgen-futures = "0.4.39"

[dev-dependencies]
tokio = { features = ["macros", "rt"], version = "1.35" }
tokio-test = "0.4.3"
