[package]
name = "proton-wallet-common"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
bdk = { version = "0.29.0", default-features = false, features = ["all-keys", "async-interface", "keys-bip39", "std"] }

# Platform-specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.10", features = ["js"] }
