[package]
name = "proton-wallet-common"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
tiny-bip39 = "1.0.0"
ripemd160 = "0.8.0"
sha2 = "0.9"
base58 = "0.1"
rand = "0.8"
secp256k1 = "0.28.0"
hex = "0.4"
hmac = "0.12.1"
sha3 = "0.10.8"
pbkdf2 = "0.12.2"