[package]
name = "andromeda-common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

bitcoin = { workspace = true }

instant = { version = "0.1", features = ["wasm-bindgen"] }
