[package]
name = "andromeda-common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
bitcoin = { version = "0.30.2", default-features = false, features = [
  "serde",
  "secp-recovery",
  "rand",
] }