[package]
name = "andromeda-api"
version = "0.1.0"
edition = "2021"

[dependencies]
andromeda-common = { version = "0.1.0", path = "../common" }
muon = { version = "0.1.0", registry = "protonvpn" }
async-std = "1.10"
cfg-if = "1"

serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0"

bitcoin = { version = "0.30.2", default-features = false, features = [
  "no-std",
  "serde",
  "secp-recovery",
  "rand",
] }

[dev-dependencies]
wiremock = "0.6.0"
tokio = { features = ["macros", "rt"], version = "1.35" }
tokio-test = "0.4.3"
muon = { version = "0.1.0", registry = "protonvpn", features = ["dangerous"] }

[features]
local = ["muon/dangerous"]
test = ["muon/dangerous"]
